/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Staff;

import DB_Operation.ApplyLc;
import DB_Operation.DB_Connectivity;
import DB_Operation.FetchLcApplicationInfo;
import DB_Operation.FetchRegistrationInfo;
import DB_Operation.LcData;
import GUI.MainFrame;
import Student.DateTime;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author 4756
 */
public class ViewLcDataFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewLcData
     */
    public static String student_id="";
    public static String lcNum="";
    public static String hod = "";
    public static String admn = "";
    public static String fee = "";
    public static String mess = "";
    public static String hostel = "";
    public static int count=0;
    
    public static String email_id="";
    
    public ViewLcDataFrame() {
        super("View LC Data                               Welcome,"+StaffDataKepper.staff_name);
        initComponents();
         Statement st = new DB_Connectivity().getConnection();
         ArrayList<String> lcInfo = new LcData().isFetchLcInfo(st, student_id);
         System.out.println(lcInfo);
         //System.out.println(lcInfo);
         jTextField4.setText(student_id);
         jTextField1.setText(lcInfo.get(0));
         jTextField2.setText(lcInfo.get(1));
         jTextField6.setText(lcInfo.get(2));
         jTextField14.setText(lcInfo.get(3));
         jTextField5.setText(lcInfo.get(4));
         jTextField3.setText(lcInfo.get(5));
         jTextField8.setText(lcInfo.get(6));
         jTextField7.setText(lcInfo.get(7));
         jTextField16.setText(lcInfo.get(8));
         jTextField15.setText(lcInfo.get(9));
         jTextField11.setText(lcInfo.get(10));
         jTextField10.setText(lcInfo.get(11));
         jTextField9.setText(lcInfo.get(12));
         jTextField12.setText(lcInfo.get(13));
         jTextField13.setText(lcInfo.get(14));
         lcNum=lcInfo.get(15);
         count=0;
         
        getStatus();
        System.out.println("Count : "+count);
         email_id = new FetchRegistrationInfo().isFetchStudentEmail(st, student_id);
         System.out.println(email_id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(217, 230, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Pulpil Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 230, 194, 47);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(380, 230, 226, 47);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Mother's Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 290, 194, 47);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(380, 290, 226, 47);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Caste");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 360, 194, 47);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(380, 550, 226, 47);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Nationality");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 420, 194, 47);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Place Of Birth");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 490, 194, 47);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(jTextField5);
        jTextField5.setBounds(380, 490, 226, 47);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Date Of Birth");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 550, 194, 47);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("DOB In Words");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 620, 194, 47);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("Last School Attended");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 690, 230, 47);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(380, 690, 230, 47);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setText("& Since When(In words & figure)  ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(890, 510, 350, 47);

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8);
        jTextField8.setBounds(380, 620, 230, 47);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setText("Date Of Addmission");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(890, 160, 221, 47);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel12.setText("Progress");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(890, 230, 221, 47);

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10);
        jTextField10.setBounds(1250, 370, 275, 47);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel13.setText("Conduct");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(890, 300, 221, 47);

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField11);
        jTextField11.setBounds(1250, 300, 275, 47);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel14.setText("Date Of Leaving School");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(890, 370, 250, 47);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel15.setText("Standard In Which Studying ");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(890, 440, 290, 47);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel16.setText("Reason Of Leaving");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(890, 620, 221, 47);

        jTextField12.setEditable(false);
        jTextField12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField12);
        jTextField12.setBounds(1250, 620, 275, 47);

        jTextField13.setEditable(false);
        jTextField13.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField13);
        jTextField13.setBounds(1250, 690, 275, 47);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel17.setText("Enrolement No.");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(890, 690, 221, 47);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        jButton1.setText("Disapprove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(790, 780, 200, 50);

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9);
        jTextField9.setBounds(1250, 440, 275, 47);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/select.png"))); // NOI18N
        jButton2.setText("Approve");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(510, 780, 200, 50);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel11.setText("Student Id");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 170, 194, 47);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(380, 170, 226, 47);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(jTextField6);
        jTextField6.setBounds(380, 360, 226, 47);

        jTextField14.setEditable(false);
        jTextField14.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(jTextField14);
        jTextField14.setBounds(380, 420, 226, 47);

        jTextField15.setEditable(false);
        jTextField15.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField15);
        jTextField15.setBounds(1250, 230, 275, 47);

        jTextField16.setEditable(false);
        jTextField16.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField16);
        jTextField16.setBounds(1250, 160, 275, 47);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setText("You are");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(470, 50, 140, 60);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "HOD", "ADMN Department", "Fee Department", "Mess Manager", "Hostel Manager" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(660, 60, 310, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(170, 40, 1580, 870);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pravara college1.jpg"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(0, 0, 1920, 1080);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(347, 40));

        jMenu1.setText("Manage Profile");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editstaff.png"))); // NOI18N
        jMenuItem1.setText("Edit Profile");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Leaving Certificate");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view.png"))); // NOI18N
        jMenuItem5.setText("Status");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Logout");
        jMenu4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:

        

    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

//        this.dispose();
//        Disapprove_Frame lf = new Disapprove_Frame();
//        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
//        lf.setSize(d);
//        lf.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String pulpilName = jTextField1.getText();
        String motherName = jTextField2.getText();
        String caste = jTextField6.getText();
        String nationality = jTextField14.getText();
        String POB = jTextField5.getText();
        String DOB = jTextField3.getText();
        String DOBW = jTextField8.getText();
        String LSA = jTextField7.getText();
        String DOA = jTextField16.getText();
        String progress = jTextField15.getText();
        String conduct = jTextField11.getText();
        String DOL = jTextField10.getText();
        String StdS = jTextField9.getText();
        String ROLS = jTextField12.getText();
        String EnNo = jTextField13.getText();
        
        
        
    
        if(StaffDataKepper.position.equals("HOD"))
        {
            hod = "Approved";
        }
        else if(StaffDataKepper.position.equals("ADMN Department"))
        {
            admn = "Approved";
        }
        else if(StaffDataKepper.position.equals("Fee Department"))
        {
            fee = "Approved";
        }
        else if(StaffDataKepper.position.equals("Mess Manager"))
        {
            mess = "Approved";
        }
        else if(StaffDataKepper.position.equals("Hostel Manager"))
        {
            hostel = "Approved";
        }
        
        if(pulpilName.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter Pulpil Name !!");
        }
        else if(motherName.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter Mother Name !!");
        }
        else if(caste.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter Caste !!");
        }
        else if(nationality.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Select Nationality !!");
        }
        else if(POB.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter Place Of Birth !!");
        }
        else if(DOB.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter Date Of Birth !!");
        }
        else if(DOBW.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter Date Of Birth in word !!");
        }
        else if(LSA.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter Last School Attended !!");
        }
        else if(DOA.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Select Date Of Admission !!");
        }
        else if(progress.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter Progress !!");
        }
        else if(conduct.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter Conduct !!");
        }
        else if(DOL.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Select Date Of Leaving School !!");
        }
        else if(StdS.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter Standard in which studying !!");
        }
        else if(ROLS.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter Reason of leaving !!");
        }
        else if(EnNo.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter Enrolement Number !!");
        }
        else if(jComboBox1.getSelectedItem().equals("Select"))
        {
            JOptionPane.showMessageDialog(null, "Please Select You Are !!");
        }
        else if(StaffDataKepper.position.equals("Addmision Department"))
        {
            if(DOL.equals("Not Known"))
            {
                JOptionPane.showMessageDialog(null, "Please Enter Date Of Leaving School !!");
            }
            if(DOA.equals("Not Known"))
            {
                JOptionPane.showMessageDialog(null, "Please Enter Date Of Leaving School !!");
            }
        }
        else 
        {
            LcData ld = new LcData();
            ApplyLc al = new ApplyLc();
            Statement st = new DB_Connectivity().getConnection();
            Statement st1 = new DB_Connectivity().getConnection();
//            getStatus();
            //count--;
            if(ld.isModifyLcData(st, student_id, pulpilName, motherName, caste, nationality, POB, DOB, DOBW, LSA, DOA, progress, conduct, DOL, StdS, ROLS, EnNo) && al.isUpdateLcApplication(st1, student_id, EnNo, StdS, pulpilName, hod, admn, fee, mess, hostel))
            {
                JOptionPane.showMessageDialog(null, " Approved Succesfully !!");
                //count=count-1;
                getStatus();
                if(count>0)
                {
                     JOptionPane.showMessageDialog(null, count+" Pending Approval !!");
                }
                else
                {
                    String date = new DateTime().getDate();
                    File f = new File(StaffDataKepper.filepath);
                    if(!f.exists())
                        f.mkdirs();
                    String filepath = StaffDataKepper.filepath+pulpilName+".pdf";
                    
                    
                    boolean flag = new PDFWriter().getTextTOPDF(filepath, lcNum, pulpilName, motherName, caste, nationality, POB, DOB, LSA, DOA, progress, conduct, DOL, StdS, ROLS, EnNo, date);
                    if(flag)
                    {
                        JOptionPane.showMessageDialog(null, " Leaving Certificate Generated Succesfully !!");
                        if(new SendMail().send(StaffDataKepper.appliedDate, pulpilName, filepath, pulpilName+".pdf", email_id))
                            JOptionPane.showMessageDialog(null, " Leaving Certificate Emailed Succesfully !!");
                    }
                    else
                        JOptionPane.showMessageDialog(null, " Error Occured in Generating Leaving Certificate!!");
                }
                
            }
            
            
            

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    public void getStatus()
    {
        Statement st = new DB_Connectivity().getConnection();
        ArrayList<String> pendingInfo = new FetchLcApplicationInfo().isStudentPendingLcApplicationInfo(st, student_id);
        System.out.println("Pending Info : "+pendingInfo);
        count = 0;
        for (int i = 0; i < pendingInfo.size(); i++) {
            if(pendingInfo.get(i).equals("pending"))
            {
                count++;
            }
            if(i==0)
            {
                hod = pendingInfo.get(i);
            }
            else if(i==1)
            {
                admn = pendingInfo.get(i);
            }
            else if(i==2)
            {
                fee = pendingInfo.get(i);
            }
            else if(i==3)
            {
                mess = pendingInfo.get(i);
            }
            else if(i==4)
            {
                hostel = pendingInfo.get(i);
            }
        }
    }
    
    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        System.out.println(StaffDataKepper.position+"    "+jComboBox1.getSelectedItem());
        if(StaffDataKepper.position.equals(jComboBox1.getSelectedItem()))
        {
            if(jComboBox1.getSelectedItem().equals("HOD"))
            {
                jTextField15.setEditable(true);
                jTextField11.setEditable(true);
            }
            else if(jComboBox1.getSelectedItem().equals("ADMN Department"))
            {
                jTextField16.setEditable(true);
                jTextField4.setEditable(true);
                jTextField1.setEditable(true);
                jTextField2.setEditable(true);
                jTextField6.setEditable(true);
                jTextField14.setEditable(true);
                jTextField5.setEditable(true);
                jTextField3.setEditable(true);
                jTextField8.setEditable(true);
                jTextField7.setEditable(true);
                jTextField16.setEditable(true);
//                jTextField15.setEditable(true);
//                jTextField11.setEditable(true);
                jTextField10.setEditable(true);
                jTextField9.setEditable(true);
                jTextField12.setEditable(true);
                jTextField13.setEditable(true);
            } 
        }
        else
            JOptionPane.showMessageDialog(null, "Please Select Your Correct Position !!");
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        StaffEditProfileFrame lf = new StaffEditProfileFrame();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        lf.setSize(d);
        lf.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LcStatusFrame lf = new LcStatusFrame();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        lf.setSize(d);
        lf.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MainFrame lf = new MainFrame();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        lf.setSize(d);
        lf.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLcDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLcDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLcDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLcDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLcDataFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
